language:
- ruby
install:
- bundle install
cache:
- bundler
script:
- bundle exec rspec
deploy:
- provider: lambda
  function_name: SyncItemMetadataToScsbListener-development
  description: A small service for listening for bib/item metadata changes to sync
    SCSB
  region: us-east-1
  role: arn:aws:iam::224280085904:role/lambda_basic_execution
  runtime: ruby2.5
  module_name: app
  handler_name: handle_event
  environment_variables:
  - PLATFORM_API_BASE_URL=https://dev-platform.nypl.org/api/v0.1/
  - NYPL_OAUTH_URL=https://isso.nypl.org/
  - NYPL_OAUTH_ID=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGowaAYJKoZIhvcNAQcGoFswWQIBADBUBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJgrQmkr7pQa4WSF1gIBEIAnLgWjuqFllMpCQWGT/eC/7n/pxFN87zaoJF19zCRHH/ulh4BICTZf
  - NYPL_OAUTH_SECRET=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAx8ZuLftGsgDmOxxBICARCAQ3ZSNw6hWlqI73kLJcs8Zg3O13PKiATfXXDUvGFim/KolFmQDCsVp7JFF9Jg01U++KNtcGJiVev7z3OAPNXc3fqGp6k=
  - SCSB_API_BASE_URL=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIAwfgYJKoZIhvcNAQcGoHEwbwIBADBqBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDC76YFNmHCel71yszwIBEIA9rRyZEpeLBxMs8wjvsVRuWXU2RoEvtYbg4GkbaRMK5c6DOKPReBD6ehzyxLQriwMBa5U30qXRDaKmSR7OIw==
  - SCSB_API_KEY=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGMwYQYJKoZIhvcNAQcGoFQwUgIBADBNBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDBGj6VVDSTYYcLzAdgIBEIAgOtoxPpUgkHHgc3eipZzyfMEUwYHIt7VvXy9Y5GRkVik=
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  on:
    branch: development
- provider: lambda
  function_name: SyncItemMetadataToScsbListener-qa
  description: A small service for listening for bib/item metadata changes to sync
    SCSB
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.5
  module_name: app
  handler_name: handle_event
  environment_variables:
  - PLATFORM_API_BASE_URL=https://qa-platform.nypl.org/api/v0.1/
  - NYPL_OAUTH_URL=https://isso.nypl.org/
  - NYPL_OAUTH_ID=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGowaAYJKoZIhvcNAQcGoFswWQIBADBUBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJgrQmkr7pQa4WSF1gIBEIAnLgWjuqFllMpCQWGT/eC/7n/pxFN87zaoJF19zCRHH/ulh4BICTZf
  - NYPL_OAUTH_SECRET=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAx8ZuLftGsgDmOxxBICARCAQ3ZSNw6hWlqI73kLJcs8Zg3O13PKiATfXXDUvGFim/KolFmQDCsVp7JFF9Jg01U++KNtcGJiVev7z3OAPNXc3fqGp6k=
  - SCSB_API_BASE_URL=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIAwfgYJKoZIhvcNAQcGoHEwbwIBADBqBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDC76YFNmHCel71yszwIBEIA9rRyZEpeLBxMs8wjvsVRuWXU2RoEvtYbg4GkbaRMK5c6DOKPReBD6ehzyxLQriwMBa5U30qXRDaKmSR7OIw==
  - SCSB_API_KEY=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGMwYQYJKoZIhvcNAQcGoFQwUgIBADBNBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDBGj6VVDSTYYcLzAdgIBEIAgOtoxPpUgkHHgc3eipZzyfMEUwYHIt7VvXy9Y5GRkVik=
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  on:
    branch: qa
- provider: lambda
  function_name: SyncItemMetadataToScsbListener-production
  description: A small service for listening for bib/item metadata changes to sync
    SCSB
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.5
  module_name: app
  handler_name: handle_event
  environment_variables:
  - PLATFORM_API_BASE_URL=https://platform.nypl.org/api/v0.1/
  - NYPL_OAUTH_URL=https://isso.nypl.org/
  - NYPL_OAUTH_ID=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGowaAYJKoZIhvcNAQcGoFswWQIBADBUBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJgrQmkr7pQa4WSF1gIBEIAnLgWjuqFllMpCQWGT/eC/7n/pxFN87zaoJF19zCRHH/ulh4BICTZf
  - NYPL_OAUTH_SECRET=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAx8ZuLftGsgDmOxxBICARCAQ3ZSNw6hWlqI73kLJcs8Zg3O13PKiATfXXDUvGFim/KolFmQDCsVp7JFF9Jg01U++KNtcGJiVev7z3OAPNXc3fqGp6k=
  - SCSB_API_BASE_URL=
  - SCSB_API_KEY=
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  on:
    branch: master
notifications:
  email:
    on_failure: always
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - secure: Im0d+4sQ1lud3h77y9V4vEWJ2nHucX9CiDva0rHKZHGlpbbxXZgTo2LFoactUWMR5Q+kRp7V8POzP26v/+RE8r2BcxV9NTFtRBDI96B0z3FoGGuQoysObOb0KoXrsDV0KxHT1IoPp28menYEO7p9WbRUQvNptAL4rsao3Y/aQ69s5TdqOVRnCGtHJLXPxGKQKbGN3shIoXnCt9h7+MlengIMjghILRFQPCHbohhJGD1P9PFVq8lRDn8VAKeffs6zWXx+qirw0hgOq2UODcTiuCoUSsMbk22TYXN+qT3F0OkBZTRtKZ6MQAk4wwz2vC5wPPj30/6ImrUcaTaPq4oHzb2PLWXvX6eeRnQR+xEW6+y5gqIiwpZZDHQW5AQXvpKoXmHytf/tCPHH4w2wombQMszI89ZzlE3SgFuE1ljxHb+ZB77rmQdamq1MRXh/Aga8ioUt/Bk31N+lNj6J/58vq8px/IU+h49tqOI21jzc3hbxHba9RYQJqRrr2SchvKkla+xAhbc/9IsAUZNys84023kTxasuwgmgwnK4qMrPJ5JSQJKL7dTrLvcauus4HxOemrhyLro2KWx/xncDhCrvRHCXGIGliEa+614kY0VCXFyQ2Ky5BPxMTgMJ5GYeSZvLeR55vLZ1+6h2ig5DJbHUqwY5H1lS7dOcpqfYLra36aw=
  - secure: KBXlfCB+WG8/NhJZBsroqS4Khdkh3xK29kRj6iWVN5SbuLZR/6NgMd2d+gRdE6I+3AV5WK7h9Ku2p+6gyyPEr0Za7z85mSLyjWaUBokAhfGLZKtYm5DEN4UjWeDWX/SHMWRppZOAhOOJLZtXpex0b3zyQrdiLQpuyiV8DHqh9r+PYWQWD0DUiOZzXYtwDsfKIGe4gA6w/IyMx4R15+FicPzJZhYE6L43Isdl+Q9MVZHWI+eagaOahYSA1H8nNfJSxyykYDDTw3DHeVfDWVAmdnEu7yPst3XKtZy0VnL5RgTRY5UgYD/5eBmkY0+4fUrTMTxRkNRiNJ0b1Hyf1GDMTY7N+iDa8ejMvRl99HnMk0Nl72xeQ+CL5+i9XGXAh256qihEIQtBJG8wO9wB9sWMbP7GZ5o05wJPcDJ+7NJAnQZzLq4tGiv6EoSWF5tYzb796N5uF6zDkDWxhDOKH9QwKSLJeOA6xPn5u1G7Nxm1v2PEAyolz4tUJ++p2/G+Ydc3/yewA0tWypeUNQdKUiNz4ZAgCyHBwEb0Glfi9sg2SgpZnjODwW68peVHmjDdL+gHMomX31/FlzHlGWDh6+/v4ChVZ7h6gBHDc+Chjxv0j+hT/4HM4vuNoXuOiH/YlOmP3i+MVEBk52K8kzaXYjoJIhcqGcv+UKPRtEYavA2xjUM=
  - secure: RhyF4vEPvskpnvqk4cmAzfVpGpjIjQAAU4Ni+EUYNRLIwssHuizUWLaH6OmSlipqnR/gzMysDZ3Lq+2JuHrXLsa1hdHBCohgwZsATeD9L5S5Nw/OStMk15aceviQTttREuAP0nryiJC0GBMH3d/sQVulgT0tEEKugFoqnkSp3l26Q1lv820gt9j6/ZFLuaNkYVgqguNWXKStwv3X1oUYfE8DblLiYXJM/Q9Zo9A/4VQjBy4NhIe63PKe1RNjQ4z/f3tWgMHKLBlWvoN8DA/dNhzPTJyk/Ev1UCALKqJ2uq8U4ZiUez1R9WyGQcHSRwwoKC/yE/6uR1jXW3LVKsmNdLJIsXzU5cL/yNipQDubUPre8LbQOMqDwmXeyKO+iyUpyvuoHUNCRYHqHp03vhjYmxEuwW/eWxlsgNCJO6Ibg7IrmTEUTR8fftsij92UmLcY7GdfvLPFoVHN9BdxdLeNlYbz+UhlIAiPMkD+MIAbwBcxwzHvkLQnwgXQE8tmcjdlK8mPu6IhKUCXEE4rfyviUGg3/ih9hy+66PlOn96RSJLcHUiNdYxsU8FR8MutGfPRLltDE1GbFkriJuL1imHIe4gBpjPyTiCG/uoeVsUglwZqUvaWc/yAtBDQro2f5Rj0M3+u40CtbvDSaTfqla2JWWYmq4lrY218YwLU1kW/03Q=
