AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sync-item-metadata-to-scsb-listener'

Resources:
  SyncItemMetadataToScsbService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handle_event
      Runtime: ruby2.5
      Timeout: 30
      Environment:
        Variables:
          PLATFORM_API_BASE_URL: 'https://qa-platform.nypl.org/api/v0.1/'
          NYPL_OAUTH_URL: https://isso.nypl.org/
          NYPL_OAUTH_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGowaAYJKoZIhvcNAQcGoFswWQIBADBUBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJgrQmkr7pQa4WSF1gIBEIAnLgWjuqFllMpCQWGT/eC/7n/pxFN87zaoJF19zCRHH/ulh4BICTZf
          NYPL_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAx8ZuLftGsgDmOxxBICARCAQ3ZSNw6hWlqI73kLJcs8Zg3O13PKiATfXXDUvGFim/KolFmQDCsVp7JFF9Jg01U++KNtcGJiVev7z3OAPNXc3fqGp6k=
          SCSB_API_BASE_URL: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIAwfgYJKoZIhvcNAQcGoHEwbwIBADBqBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDC76YFNmHCel71yszwIBEIA9rRyZEpeLBxMs8wjvsVRuWXU2RoEvtYbg4GkbaRMK5c6DOKPReBD6ehzyxLQriwMBa5U30qXRDaKmSR7OIw==
          SCSB_API_KEY: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGMwYQYJKoZIhvcNAQcGoFQwUgIBADBNBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDBGj6VVDSTYYcLzAdgIBEIAgOtoxPpUgkHHgc3eipZzyfMEUwYHIt7VvXy9Y5GRkVik=
          NOTIFICATION_EMAIL: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHMwcQYJKoZIhvcNAQcGoGQwYgIBADBdBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDIJI11++bttShr1irwIBEIAwF0xNvg3mkAIna3pOEPhnm7+2wVqnvhWHk9BN1ImBbfW9kPcqUVImyKfGl2w25KjB
          LOG_LEVEL: debug
